Vagrant.configure("2") do |config|
    # Configure the box to use
    config.vm.box = 'geerlingguy/ubuntu1604'

    # Configure the network interfaces
    config.vm.network :private_network, ip: "192.168.33.10"

    # Configure shared folders
    config.vm.synced_folder "../", "/var/www/symfony", id: "symfony", type: 'nfs', :nfs => { :mount_options => ["dmode=777","fmode=666"] }

    # Configure VirtualBox environment
    config.vm.provider :virtualbox do |v|
        v.name = "symfony.vm"
        v.memory = 1024
        v.cpus = 2
        v.linked_clone = true
    end

    # Provision the box
    config.vm.provision :ansible do |ansible|
        ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
        ansible.playbook = "ansible/stages/vagrant.yml"
        ansible.sudo = true
    end
end
